// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdtqhgjdybkrbfupwsfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkdHFoZ2pkeWJrcmJmdXB3c2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjgyOTMsImV4cCI6MjA1ODgwNDI5M30.HX1eYhHhce_a9xz0-2bGMiNSQJX5C3wmWYIgrcczIAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);